# Generated by Django 3.2.7 on 2021-09-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0002_auto_20210908_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
